title:              goat.sportscards
email:              domenicfayad@gmail.com
description:        High-end sports card collection
#author:             Start Bootstrap
#baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://goatsportscards.github.io"

# Social Profiles
twitter_username:   domenic.fayad
github_username:    dmf95
#facebook_username:  StartBootstrap
instagram_username:  goat.sportscards
linkedin_username:

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
